services:
  - type: web
    name: frontend
    env: node
    repo: https://github.com/CADSTER-Technologies/CADSTERA
    branch: main
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    rootDir: frontend
  - type: web
    name: backend
    env: python
    repo: https://github.com/CADSTER-Technologies/CADSTERA
    branch: main
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python main.py
    rootDir: backend
